### ISSUE TITLE
Backend - Understand localStorage thoroughly

### ISSUE THREAD

**Issue by kylenzhong** [cse110-fa21-group14/cse110-fa21-group14#12]

**Comment by kylenzhong** [comment]
Here are the functions that need to be supported:

- Initialize localStorage
- Store information in localStorage with key, value pair
- Iterate through all information stored in localStorage
- Retrieve information based on a key
- Edit the value of information stored

**Comment by lakuo** [comment]
- localStorage comes pre-initialized in browsers
- Store/update values:
   - `localStorage.setItem(key,value)`
   - key = recipe name, value = stringified JSON data
- Iterate through localStorage:
    ``` 
    Object.keys(localStorage).forEach(function(key){
        console.log(localStorage.getItem(key));
    });
    ```
    - idea: function to convert all localStorage data to objects, then search
- Retrieve information:
   ```
   localStorage.getItem(key)
   ```
- Remove information:
   ```
   localStorage.removeItem(key)
   ```
